/*****************************************************************************
  AUTO-GENERATED CODE:  Microchip MPFS Generator version: 2.2.2

  Microchip TCP/IP Stack Application Demo

  Company:
    Microchip Technology Inc.

  File Name:
    http_print.h

  Summary:
    This file is automatically generated by the MPFS Generator Utility.
    ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR.

  Description:
    Provides callback headers and resolution for user's custom
    HTTP Application.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
Software License Agreement
Copyright(c) 2014 Microchip Technology Inc. All rights reserved.
Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital
signal controller that is integrated into your product or third party
product (pursuant to the sublicense terms in the accompanying license
agreement).

You should refer to the license agreement accompanying this Software
for additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef __HTTPPRINT_H_
#define __HTTPPRINT_H_

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include "tcpip/tcpip.h"

/*****************************************************************************
 * SECTION:  Global Variables
 *****************************************************************************/
#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern uint8_t curHTTPID;

/*****************************************************************************
 * SECTION:  Generated Function Prototypes
 *****************************************************************************/
void HTTPPrint(uint32_t callbackID);
void HTTPPrint_ssid(void);
void HTTPPrint_curPrivacy(void);
void HTTPPrint_wlan(void);
void HTTPPrint_ipaddr(void);
void HTTPPrint_fwver(void);
void HTTPPrint_led(uint16_t);
void HTTPPrint_nextSSID(void);
void HTTPPrint_prevSSID(void);
void HTTPPrint_prevWLAN(void);
void HTTPPrint_nextWLAN(void);
void HTTPPrint_scan(void);
void HTTPPrint_bssCount(void);
void HTTPPrint_valid(void);
void HTTPPrint_name(void);
void HTTPPrint_privacy(void);
void HTTPPrint_strength(void);
void HTTPPrint_btn(uint16_t);

/*****************************************************************************
 * FUNCTION: HTTPPrint
 *
 * RETURNS:  None
 *
 * PARAMS:   callbackID
 *****************************************************************************/
void HTTPPrint(uint32_t callbackID)
{
   switch(callbackID)
   {
        case 0x00000000:
			HTTPPrint_ssid();
			break;
        case 0x00000001:
			HTTPPrint_curPrivacy();
			break;
        case 0x00000002:
			HTTPPrint_wlan();
			break;
        case 0x00000003:
			HTTPPrint_ipaddr();
			break;
        case 0x00000004:
			HTTPPrint_fwver();
			break;
        case 0x00000005:
			HTTPPrint_led(0);
			break;
        case 0x00000006:
			HTTPPrint_nextSSID();
			break;
        case 0x00000007:
			HTTPPrint_prevSSID();
			break;
        case 0x00000008:
			HTTPPrint_prevWLAN();
			break;
        case 0x00000009:
			HTTPPrint_nextWLAN();
			break;
        case 0x0000000a:
			HTTPPrint_scan();
			break;
        case 0x0000000b:
			HTTPPrint_bssCount();
			break;
        case 0x0000000c:
			HTTPPrint_valid();
			break;
        case 0x0000000d:
			HTTPPrint_name();
			break;
        case 0x0000000e:
			HTTPPrint_privacy();
			break;
        case 0x0000000f:
			HTTPPrint_strength();
			break;
        case 0x00000010:
			HTTPPrint_led(1);
			break;
        case 0x00000011:
			HTTPPrint_led(2);
			break;
        case 0x00000012:
			HTTPPrint_btn(0);
			break;
       default:
           // Output notification for undefined values
           TCPPutROMArray(sktHTTP, (ROM uint8_t*)"!DEF", 4);
   }

   return;
}

void HTTPPrint_(void)
{
   TCPPut(sktHTTP, '~');
   return;
}

#endif /*STACK_USE_HTTP2_SERVER*/

#endif /*__HTTPPRINT_H_*/
